import * as React from "react";
import FileUpload from "@cloudscape-design/components/file-upload";
import FormField from "@cloudscape-design/components/form-field";
import Header from "@cloudscape-design/components/header";
import Form from "@cloudscape-design/components/form";
import SpaceBetween from "@cloudscape-design/components/space-between";
import Button from "@cloudscape-design/components/button";
import Container from "@cloudscape-design/components/container";
import Input from "@cloudscape-design/components/input";

export default () => {
  const [value, setValue] = React.useState([]);
  return (
    <form onSubmit={e => e.preventDefault()}>
      <Form
        actions={
          <SpaceBetween direction="horizontal" size="xs">
            <Button formAction="none" variant="link">
              Cancel
            </Button>
            <Button variant="primary">Submit</Button>
          </SpaceBetween>
        }
        header={<Header variant="h1">Analyze Workload Costs</Header>}
      >
        <Container
          header={
            <Header variant="h2">
              Upload Cost and Usage report
            </Header>
          }
        >
          <SpaceBetween direction="vertical" size="l">
            <FormField label="AWS Account ID">
              <Input />
            </FormField>
                <FormField
                label="Select a file"
                description="Please upload a file generated by AWS Cost and Usage Report"
                >
                <FileUpload
                    onChange={({ detail }) => setValue(detail.value)}
                    value={value}
                    i18nStrings={{
                    uploadButtonText: e =>
                        e ? "Choose files" : "Choose file",
                    dropzoneText: e =>
                        e
                        ? "Drop files to upload"
                        : "Drop file to upload",
                    removeFileAriaLabel: e =>
                        `Remove file ${e + 1}`,
                    limitShowFewer: "Show fewer files",
                    limitShowMore: "Show more files",
                    errorIconAriaLabel: "Error"
                    }}
                    showFileLastModified
                    showFileSize
                    showFileThumbnail
                    tokenLimit={3}
                    constraintText="Supported formats are: "
                />
                </FormField>
          </SpaceBetween>
        </Container>
      </Form>
    </form>
  );
}
    // <Board>
    // <BoardItem 
    // header={<Header>Upload Files</Header>}
    // i18nStrings={{
    //     dragHandleAriaLabel: "Drag handle",
    //   }}>
    // <FormField
    //   label="Form field label"
    //   description="Description"
    // >
    //   <FileUpload
    //     onChange={({ detail }) => setValue(detail.value)}
    //     value={value}
    //     i18nStrings={{
    //       uploadButtonText: e =>
    //         e ? "Choose files" : "Choose file",
    //       dropzoneText: e =>
    //         e
    //           ? "Drop files to upload"
    //           : "Drop file to upload",
    //       removeFileAriaLabel: e =>
    //         `Remove file ${e + 1}`,
    //       limitShowFewer: "Show fewer files",
    //       limitShowMore: "Show more files",
    //       errorIconAriaLabel: "Error"
    //     }}
    //     showFileLastModified
    //     showFileSize
    //     showFileThumbnail
    //     tokenLimit={3}
    //     constraintText="Hint text for file requirements"
    //   />
    // </FormField>
    // </BoardItem>

    // </Board>
   
//   );
// }